-- MySQL Script generated by MySQL Workbench
-- Sun Apr 12 12:42:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fifa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fifa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fifa` DEFAULT CHARACTER SET utf8 ;
USE `fifa` ;

-- -----------------------------------------------------
-- Table `fifa`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifa`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`Time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifa`.`Time` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `fifa`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`Jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifa`.`Jogador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(10) NOT NULL,
  `posicao` ENUM('Zagueiro', 'Volante', 'Meia', 'Atacante', 'Lateral D', 'Lateral E') NOT NULL,
  `idTime` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_time_idx` (`idTime` ASC) VISIBLE,
  CONSTRAINT `id_time`
    FOREIGN KEY (`idTime`)
    REFERENCES `fifa`.`Time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`Campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifa`.`Campeonato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTime` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_time_idx` (`idTime` ASC) VISIBLE,
  CONSTRAINT `id_time_camp`
    FOREIGN KEY (`idTime`)
    REFERENCES `fifa`.`Time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifa`.`Partida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `localTime` DATETIME NOT NULL,
  `idCampeonato` INT NOT NULL,
  `idPrimeiroTime` INT NOT NULL,
  `idSegundoTime` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_campeonato_idx` (`idCampeonato` ASC) VISIBLE,
  CONSTRAINT `id_primeiro_time`
    FOREIGN KEY (`idPrimeiroTime`)
    REFERENCES `fifa`.`Time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_segundo_time`
    FOREIGN KEY (`idSegundoTime`)
    REFERENCES `fifa`.`Time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_campeonato`
    FOREIGN KEY (`idCampeonato`)
    REFERENCES `fifa`.`Campeonato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`Gol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fifa`.`Gol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tempo` VARCHAR(10) NOT NULL,
  `idPartida` INT NOT NULL,
  `idJogador` INT NOT NULL,
  `idTime` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_partida_idx` (`idPartida` ASC) VISIBLE,
  INDEX `id_jogador_idx` (`idJogador` ASC) VISIBLE,
  INDEX `id_time_idx` (`idTime` ASC) VISIBLE,
  CONSTRAINT `id_partida`
    FOREIGN KEY (`idPartida`)
    REFERENCES `fifa`.`Partida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_jogador`
    FOREIGN KEY (`idJogador`)
    REFERENCES `fifa`.`Jogador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_time_gol`
    FOREIGN KEY (`idTime`)
    REFERENCES `fifa`.`Time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
